-- 1. Create PORTAFOLIO table
CREATE TABLE IF NOT EXISTS portafolio (
    id_portafolio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trabajador INTEGER REFERENCES trabajador(id_trabajador),
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT,
    foto_url TEXT NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add url_documento to CERTIFICACION table (if not exists)
-- Note: The table name in clean_data.sql is TRABAJADOR_CERTIFICACION, but in mockData/api it seems we use that.
-- Let's check the schema. Assuming TRABAJADOR_CERTIFICACION links to CERTIFICACION.
-- Actually, looking at api.ts: 
-- from('trabajador_certificacion').select(certificacion:certificacion_id_certificacion(...))
-- So the actual data is in CERTIFICACION table.

ALTER TABLE certificacion 
ADD COLUMN IF NOT EXISTS url_documento TEXT;

-- 3. Add customization fields to PERFIL table
ALTER TABLE perfil
ADD COLUMN IF NOT EXISTS banner_url TEXT,
ADD COLUMN IF NOT EXISTS color_tema VARCHAR(20) DEFAULT 'indigo'; -- e.g., 'indigo', 'blue', 'green'

-- 4. Add index for portfolio
CREATE INDEX IF NOT EXISTS idx_portafolio_trabajador ON portafolio(id_trabajador);
