-- Create MENSAJE table for chat history
CREATE TABLE MENSAJE (
  id_mensaje BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_solicitud BIGINT REFERENCES SOLICITUD_SERVICIO(id_solicitud),
  id_remitente INTEGER REFERENCES PERSONA(id_persona),
  contenido TEXT NOT NULL,
  fecha_envio TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for faster queries
CREATE INDEX idx_mensaje_solicitud ON MENSAJE(id_solicitud);
