-- =================================================================
-- SCRIPT DE LIMPIEZA DE DATOS
-- =================================================================
-- Este script elimina todos los datos de las tablas para permitir pruebas limpias.
-- Se usa TRUNCATE ... CASCADE para manejar las dependencias de claves foráneas.

-- Tablas principales de usuarios y perfiles
-- Tablas de Chat y Solicitudes
TRUNCATE TABLE MENSAJE CASCADE;
TRUNCATE TABLE CALIFICACION CASCADE;
TRUNCATE TABLE SOLICITUD_SERVICIO CASCADE;

-- Tablas de Suscripción
TRUNCATE TABLE MEMBRESIA CASCADE;
-- TRUNCATE TABLE PLAN CASCADE; -- Datos estáticos, no borrar

-- Tablas principales de usuarios y perfiles
TRUNCATE TABLE PUBLICACION CASCADE;
TRUNCATE TABLE CURRICULUM CASCADE;
TRUNCATE TABLE TRABAJADOR_CERTIFICACION CASCADE;
TRUNCATE TABLE TRABAJADOR_SERVICIO CASCADE;
TRUNCATE TABLE TRABAJADOR_COMUNA CASCADE;
TRUNCATE TABLE SERVICIO_CATEGORIA_SERVICIO CASCADE;
TRUNCATE TABLE SERVICIO CASCADE; -- Ahora contiene datos de usuario
TRUNCATE TABLE COMUNA_CLIENTE CASCADE;
TRUNCATE TABLE PERFIL CASCADE;
TRUNCATE TABLE TRABAJADOR CASCADE;
TRUNCATE TABLE CLIENTE CASCADE;
TRUNCATE TABLE PERSONA CASCADE;

-- Tablas de referencia (Opcional: descomentar si se desea limpiar también)
-- TRUNCATE TABLE CERTIFICACION CASCADE;
-- TRUNCATE TABLE COMUNA CASCADE;
-- TRUNCATE TABLE CIUDAD CASCADE;
-- TRUNCATE TABLE REGION CASCADE;
-- TRUNCATE TABLE PAIS CASCADE;
-- TRUNCATE TABLE CATEGORIA_SERVICIO CASCADE;

-- Tabla de reportes
TRUNCATE TABLE REPORTE_MEMBRESIA_TRABAJADOR CASCADE;
